"""Write docs/WIRING.md: which sprig goes on which twig, its channel, chain position and hub slot."""
import math, os, sys
import tree_gen as TG
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "electronics", "tools"))
import hub_layout as H  # noqa: E402

t = TG.Tree()
rows = []
for tp in t.tips:
    x, y, z = tp["pos"]
    az = math.degrees(math.atan2(x - TG.BURL[0], y - TG.BURL[1])) % 360
    slot = H.sprig_slot(tp["channel"], tp["index"])
    rows.append((tp["channel"], tp["index"], tp["name"], tp["limb"] + 1, az, z, slot, H.slot_angle(slot)))
rows.sort()
out = ["# ECLIPSE Tree - sprig wiring map", "",
       "Generated by `mechanical/wiring_map.py` from the seeded tree (`tree_gen.SEED`).",
       "Each sprig's magnet-wire pair (A = red enamel, K = clear) runs back along its branch to the",
       "hub land pair at the listed slot (slot 0 = rear, clockwise seen from above).", "",
       "| Sprig | Channel | Chain pos | Limb | Twig azimuth | Twig height | Hub slot | Slot angle |",
       "|---|---|---:|---:|---:|---:|---:|---:|"]
for ch, k, name, limb, az, z, slot, sa in rows:
    out.append(f"| {name} | {ch} | {k + 1} | {limb} | {az:5.0f}° | {z:5.0f} mm | {slot} | {sa:5.1f}° |")
out += ["", "Hub ref S1-S40 = channel order W1, C1, W2, C2, ten each, in chain order."]
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "docs", "WIRING.md"), "w").write("\n".join(out) + "\n")
print(len(rows), "sprigs mapped")
